---
title: "The anominysing script"
author: "NN"
date: "11/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Loading packages
```{r loading packages, include = FALSE}

pacman::p_load(
  brms,
  tidyverse,
  here,
  tidybayes,
  LaplacesDemon,
  tidyr,
  reshape2,
  digest)

# RF: to define path use here() much more elegant :-)

```

#Loading data and merging

```{r loading main data include = FALSE}
#Listing files in path
files <- list.files(path = here("Gender_bias_study_1", "data"))

#Create empty data frame
data <- data.frame(matrix(ncol = 36, nrow = 0))

#Looping through data files and inserting in dataframe
for (i in files) {
  d <- read.delim(file = paste(here("Gender_bias_study_1", "data"),"/", i, sep = ""), sep = ",", header = TRUE)
  data = rbind(data,d)
}

```

```{r loading data with different amount of trials}

#Listing files in directory
kiri_files <- list.files(path = here("Gender_bias_study_1", "kiri"), pattern = "*.csv") 

#Creating empty data frame
kiri_data <- data.frame(matrix(ncol = 35, nrow = 0))

#Looping through Kiri data 
for (i in kiri_files) {
  d <- read.delim(file = paste(here("Gender_bias_study_1", "kiri"),"/", i, sep = ""), sep = ",", header = TRUE, stringsAsFactors = FALSE)
  kiri_data = rbind(kiri_data, d)
}

```


```{r}
#Merge the two dataframes
kiri_data <- add_column(kiri_data, Computer = "Two screens", .after = 4)
data <- rbind(data, kiri_data)
```


#Data cleaning
```{r cleaning data, include = FALSE}

data <- data %>%
  subset(
    select = -c(X) #Removing column of x
    ) %>%
  mutate(
    GroupNumber = parse_number(GroupNumber) #Cleaning group numbers
  )


#Cleaning subject IDs
data$SubjectID_left <- as.character(data$SubjectID_left)
data$SubjectID_right <- as.character(data$SubjectID_right)
data$SubjectID_left[data$SubjectID_left == "steph"] <- "stephanie"
data$SubjectID_right[data$SubjectID_right == "Emil"] <- "emil"
data$SubjectID_right[data$SubjectID_right == "Sebber"] <- "seb"
data$SubjectID_left[data$SubjectID_left == "signe"] <- "SigneR"
data$SubjectID_right[data$SubjectID_right == "karo"] <- "Karoline"
data$SubjectID_right[data$SubjectID_right == "tobias"] <- "Toby"
data$SubjectID_left[data$SubjectID_left == "Nina"] <- "nina"
data$SubjectID_right[data$SubjectID_right == "theasmom"] <- "Theasmom"
data$SubjectID_left[data$SubjectID_left == "emma"] <- "Emma"
data$SubjectID_right[data$SubjectID_right == "LasseKob"] <- "Lasse"
```

#Anonymise
```{r}
#Creating anonymise-function
anonymize <- function(x, algo="crc32"){
  unq_hashes <- vapply(unique(x), function(object) digest(object, algo=algo), FUN.VALUE="", USE.NAMES=TRUE)
  unname(unq_hashes[x])
}
#Duplicating the data 
data_a = data

#Anonymising the duplicated data
data_a$SubjectID_left <- anonymize(data$SubjectID_left)
data_a$SubjectID_right <- anonymize(data$SubjectID_right)

```

#Delete confidence variable

```{r dummy code response variable ---> delete confidence variable}

data_a$Response_left <- ifelse(data_a$Response_left < 0, 0,1)
data_a$Response_right <- ifelse(data_a$Response_right < 0, 0,1)

```



#Create CSV
```{r}
write.csv(data_a, file = "anonymised_data.csv")

```

