---
title: "preprocessing_decision_bias"
author: "Thea Rolskov Sloth"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setting working directories and loading data
```{r loading packages and data}
library(pacman)
p_load(plotly, jpeg, tm, brms, tidyverse, tidybayes, ggplot2, LaplacesDemon, rethinking, tidyr, reshape2, tibble)

#Setting working directory
setwd("~/gender_bias_in_decision_making/Gender_bias_study_2")
path_db = ("decision_data/")

#Listing files in path
files <- list.files(path = path_db)

#Create empty data frame
data_db <- data.frame(matrix(ncol = 30, nrow = 0))

#Looping through data files and inserting in dataframe
for (i in files) {
  d <- read.delim(file = paste(path_db, i, sep = ""), sep = ",", header = TRUE)
  data_db = rbind(data_db,d)
}

#Renaming Kiri's trial
data_db$SubjectID_left[data_db$SubjectID_left == "25_kk"] <- "25_KK"

#Removing the useless column of X
data_db <- subset(data_db, select = -c(X))

```

```{r make a column with unique group ID}
#Creating a column with unique group ID's
data_db$SubjectID_left <- as.character(data_db$SubjectID_left)
data_db$SubjectID_right <- as.character(data_db$SubjectID_right)

data_db$group_id <- as.character(paste(data_db$SubjectID_left,"_",data_db$SubjectID_right, sep = ""))
```

```{r make a column with unique subject ID}
#Creating a column with unique subject ID's
data_db$SubjectID_left_unique <- as.character(paste(data_db$SubjectID_left,"_",data_db$Round, sep = ""))
data_db$SubjectID_right_unique <- as.character(paste(data_db$SubjectID_right,"_",data_db$Round, sep = ""))

```


```{r difficulty measure for all colors}

#Making a column that expresses difficulty
data_db <- data_db %>%
  mutate(diff = ifelse(Block == "blå", (Prop_blue_image_2 - Prop_blue_image_1), ifelse(Block == "rød", (Prop_red_image_2 - Prop_red_image_1), ifelse(Block == "grøn", (Prop_green_image_2 - Prop_green_image_1), ifelse(Block == "gul", (Prop_yellow_image_2 - Prop_yellow_image_1), NA)))))

```

```{r dummy coding answers: 0 = left picture, 1 = right picture}

#Making a column that expresses the participants' answer, 0 = left picture, 1 = right picture
data_db$response_right_dummy <- ifelse(data_db$Response_right > 0, 1, 0)
data_db$response_left_dummy<- ifelse(data_db$Response_left > 0, 1, 0)

#Joining joint answer to one column; the final decision
data_db$response_joint_dummy <- data_db$Joint_right+ data_db$Joint_left

#Recoding joint answer to be 0 and 1's, 0 right, 1 left, NA = no leader
data_db$response_joint_dummy[data_db$response_joint_dummy == 0] <- NA #Replacing 0's with NA
data_db$response_joint_dummy[data_db$response_joint_dummy == -1] <- 0

```

#Leader and follower
```{r dummy code leader and follower}

data_db$chosen_leader <- NA

#Create a column that sorts out all the "agree trials"
data_db$chosen_leader <- ifelse(data_db$response_right_dummy == data_db$response_left_dummy, "Agree", 0) 

#Create a variable that determines the chosen leader
data_db$chosen_leader[data_db$chosen_leader == 0 & data_db$Joint_right == 0] <- "Left_lead"
data_db$chosen_leader[data_db$chosen_leader == 0 & data_db$Joint_left == 0] <- "Right_lead"

#Create column that specifies the gender of the leader
data_db$Leader_gender <- 0
data_db$Leader_gender <- ifelse(data_db$chosen_leader == "Left_lead", as.character(data_db$Gender_left), as.character(data_db$Gender_right))
data_db$Leader_gender[data_db$chosen_leader == "Agree"] <- NA

#Create column that specifies the gender of the follower
data_db$Follower_gender <- 0
data_db$Follower_gender <- ifelse(data_db$chosen_leader == "Left_lead", as.character(data_db$Gender_right), as.character(data_db$Gender_left))
data_db$Follower_gender[data_db$chosen_leader == "Agree"] <- NA

```

#Did the leader stick to its own initial answer or surrender to their follower's initial answer?
```{r did the leader stick?}

#Creating column that expresses the leader's behavior
data_db$leader_behavior <- 0 #Creating column of 0's

#Inserting cases were leader stick for right leader
data_db$leader_behavior[data_db$chosen_leader == "Right_lead" & data_db$response_joint_dummy == data_db$response_right_dummy] <- "stick" 

#Inserting cases were leader surrender for right leader
data_db$leader_behavior[data_db$chosen_leader == "Right_lead" & data_db$response_joint_dummy != data_db$response_right_dummy] <- "surrender" 


#Inserting cases were leader stick for left leader
data_db$leader_behavior[data_db$chosen_leader == "Left_lead" & data_db$response_joint_dummy == data_db$response_left_dummy] <- "stick" 

#Inserting cases were leader surreder for left leader
data_db$leader_behavior[data_db$chosen_leader == "Left_lead" & data_db$response_joint_dummy != data_db$response_left_dummy] <- "surrender" 

#Replacing agree cases with NA's
data_db$leader_behavior[data_db$chosen_leader == "Agree"] <- NA 

```


```{r Add trial variable}

#Creating a trial variable in a dataframe; data_j
n = 1
p = NULL
 for (p in unique(data_db$SubjectID_left_unique)){
   if (n == 1) {
     data_j <- filter(data_db, data_db$SubjectID_left_unique == p)
     data_j <- cbind(data_j, as.data.frame(1:sum(complete.cases(data_j$SubjectID_left))))
     colnames(data_j)[41] <- "Trial"
     n = n + 1
     } else {
     data_j <- rbind(data_j,mutate(filter(data_db, data_db$SubjectID_left_unique == p), Trial = 1:sum(complete.cases(filter(data_db, data_db$SubjectID_left_unique == p)$SubjectID_left))))
     n = n + 1
   }
 }

```


```{r Filtering data to include only joint decisions}
#Filtering data to include only disagree trials/joint decisions
disagree_db <- na.omit(data_j)

```

#Write csv-files
```{r save clean data files, eval=F}

write.csv(data_db, file = "data_GBDM.csv")
write.csv(disagree_db, file = "disagree_data_GBDM.csv")

```

